name: CI

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0']

        name: PHP ${{ matrix.php }} tests
        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none
                    tools: phpunit

            -   run: composer require psr/log psr/container
            -   run: phpunit -v --colors=always tests
